#include <mpi.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <math.h>

#define ARRAY_SIZE 1000 // Adjust the size of the array as needed
#define RANDOM_NUMBER_MAX_SIZE ARRAY_SIZE * 100

void generateArray(int *array, int start, int end, int arraySize){

    // Seed the random number generator
    srand(time(NULL));

    // Generate random numbers within the range and store them in the array
    for (int i = 0; i < arraySize; i++) {
        array[i] = rand() % (end - start + 1) + start;
    }

    // Sort the array in ascending order
    for (int i = 0; i < arraySize - 1; i++) {
        for (int j = 0; j < arraySize - i - 1; j++) {
            if (array[j] > array[j + 1]) {
                int temp = array[j];
                array[j] = array[j + 1];
                array[j + 1] = temp;
            }
        }
    }
}

void calculateRange(int total_elements, int num_processes, int rank, int *start_range, int *end_range) {
    
    // Calculate the size of each chunk and the remainder    
    int chunk_size = total_elements / num_processes;
    int remainder = total_elements % num_processes;

    // Initialize the starting point of the range
    int start = total_elements - 1;

    // Adjust the starting point based on the rank of the process
    for (int i = 0; i < rank; i++) {

        // Move the start backward by chunk size
        start -= chunk_size;
        if (remainder > 0) {

            // Adjust for any remaining elements
            start--;
            remainder--;
        }
    }

    // Calculate the end point of the range
    int end = start - chunk_size + 1;
    if (remainder > 0) {
        end--;
    }

    // Assign the calculated start and end points to the output variables
    *start_range = end;
    *end_range = start;

}

void printArray(int *array, int size, int rank) {
    printf("Rank: %d Array: ", rank);
    printf("[ ");
    for (int i = 0; i < size; i++) {
        printf("%d ", array[i]);
        if ((i + 1) % 10 == 0)
            printf("\n  ");
    }
    printf("]\n");
}

int main(int argc, char *argv[]) {

    int rank, size;
    double start_time, end_time, elapsed_time, tick;
    
    MPI_Init(&argc, &argv);
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);
    MPI_Comm_size(MPI_COMM_WORLD, &size);

    // Returns the precision of the results returned by MPI_Wtime
    tick = MPI_Wtick();

    // Ensures all processes will enter the measured section of the code at the same time
    MPI_Barrier(MPI_COMM_WORLD);

    start_time = MPI_Wtime();

    int start_range, end_range;

    // Calculate the range of elements for the current process
    calculateRange(RANDOM_NUMBER_MAX_SIZE, size, rank, &start_range, &end_range);

    printf("Rank %d: Start = %d, End = %d\n", rank, start_range, end_range);

    int *sortedRandomIntegerArray = (int *)malloc(ARRAY_SIZE * sizeof(int));

    // Generate the array of random integers for the current process
    generateArray(sortedRandomIntegerArray, start_range, end_range, ARRAY_SIZE);

    // Ensures all processes will enter the measured section of the code at the same time
    MPI_Barrier(MPI_COMM_WORLD);

    end_time = MPI_Wtime(); 

    if (rank == 0) {

        // Array to store received arrays
        int receivedArrays[size][ARRAY_SIZE]; 
        MPI_Status status;
        
        printf("********* Receive Arrays *********\n");

        // Receive arrays from all processes except for rank 0
        for (int source = 1; source < size; source++) {
            MPI_Recv(receivedArrays[source], ARRAY_SIZE, MPI_INT, source, 0, MPI_COMM_WORLD, &status);
            printArray(receivedArrays[source], ARRAY_SIZE, source);
            printf("\n");
        }

        // Print the array generated by rank 0
        printArray(sortedRandomIntegerArray, ARRAY_SIZE, rank);

    } else {
    
        // Send the array generated by other processes to rank 0
        MPI_Send(sortedRandomIntegerArray, ARRAY_SIZE, MPI_INT, 0, 0, MPI_COMM_WORLD);
    }
    
    // Calculate the elapsed time
    elapsed_time = end_time - start_time;

    if (rank == 0) {
        printf("Total processes: %d\n", size);
        printf("Total computation time: %e seconds\n", elapsed_time);
        printf("Computation time per process: %e seconds\n", elapsed_time / size);
        printf("Resolution of MPI_Wtime: %e seconds\n", tick);
    }

    MPI_Finalize();

    return 0;
}
